name: visual-coding
version: "0.1.0.0"
author: Hannes Steffenhagen
maintainer: "Hannes Steffenhagen <cubicentertain@gmail.com>"

dependencies:
- base >= 4.14.3.0

default-extensions:
- AllowAmbiguousTypes
- DeriveGeneric
- DerivingStrategies
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src
  dependencies:
  - yesod

executables:
  visual-coding:
    main: Main.hs
    source-dirs: app
    dependencies:
    - visual-coding
    - yesod

tests:
  unit:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - visual-coding
    - hspec >= 2.9.6
    - yesod-test
    build-tools:
    - hspec-discover >= 2.9.6
